"""empty message

Revision ID: dd856838d334
Revises: c1060d834140
Create Date: 2024-08-23 00:35:14.018709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd856838d334'
down_revision: Union[str, None] = 'c1060d834140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('football_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_football_results_id'), 'football_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_football_results_id'), table_name='football_results')
    op.drop_table('football_results')
    # ### end Alembic commands ###
